steps:

  # Install dependencies
  - name: 'python:3.8'
    entrypoint: pip
    args: [ "instalal", "-r", "requirements.txt", "--user" ]


  # Build the serving container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '.', '-t', 'us-central1-docker.pkg.dev/llm-dolly/nashtech-ai-docker-registry/llm-dolly-serve-image:0.1', '-f', 'serving_container/Dockerfile' ]
    id: 'build'


  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/llm-dolly/nashtech-ai-docker-registry/llm-dolly-serve-image:0.1' ]
    id: 'push'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/curl'
    id: 'send_notification'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "master" ]; then
          BUILD_LOGS="$(gcloud builds log "$BUILD_ID")"
          if [[ $BUILD_LOGS == *"ERROR"* || $BUILD_LOGS == *"FAILURE"* ]]; then
            echo "Sending build failure notification..."
            curl -X POST \
              --url "smtp.gmail.com" \
              --ssl-reqd \
              --mail-from "kubeflow35@gmail.com" \
              --mail-rcpt "aman.srivastava@knoldus.com" \
              --user "kubeflow35@gmail.com.com:bodlerhhhuisjtgo" \
              --insecure \
              --upload-file <(echo -e "From: kubeflow35@gmail.com\nTo: aman.srivastava@knoldus.com\nSubject: Build Failed\n\nBuild has failed. Check the logs for more details.")
          fi
        fi  

options:
  logging: CLOUD_LOGGING_ONLY
